`ifndef OR_BE_TYPES_PKG_SV
`define OR_BE_TYPES_PKG_SV

// OR-BE backend types.
//
// Scope: exactly the frozen cross-stage schema plus the event batches that
// more than one module names.  Anything already frozen elsewhere is imported
// rather than restated.
//
//   exe_subop / G3 classification      exe_subop_pkg.sv          (frozen)
//   LSU payloads, tag width, capacity  or_be_lsu_protocol_pkg.sv (frozen)
//
// The schema freezes widths and encodings only, not packed field order, so
// the orders below are a local choice.  The total widths (IB_Payload 294 /
// decoded_info 112 / ISQ_Payload 556) are checked by
// or_be_types_check.sv.
package or_be_types_pkg;

    import exe_subop_pkg::*;
    import or_be_lsu_protocol_pkg::*;

    // ---------------------------------------------------------------------
    // Machine constants
    // ---------------------------------------------------------------------

    // Architectural register width.
    localparam int XLEN = 64;

    // FP register width.  RV64 with D means FLEN == XLEN == 64; they are
    // separate concepts that happen to agree, same as XLEN vs LSU_DATA_W.
    localparam int FLEN = 64;

    // ROB / SCB slot handle.  The LSU contract froze it at 4 bits and a tag is
    // the slot number itself, so the two are the same quantity -- take the
    // frozen one rather than declaring a second 4.
    localparam int TAG_W      = LSU_TAG_W;
    localparam int ROB_DEPTH  = 1 << TAG_W;              // 16

    // IB pointers are {loopbit, index[2:0]}.
    localparam int IB_DEPTH   = 8;
    localparam int IB_PTR_W   = $clog2(IB_DEPTH) + 1;    // 4

    // SCB pointers are 5-bit {loopbit, index[3:0]}.
    localparam int ROB_PTR_W  = TAG_W + 1;               // 5

    localparam int REG_ADDR_W = 5;
    localparam int NUM_GPR    = 32;
    localparam int NUM_FPR    = 32;

    // Two dispatch slots and two retire lanes; four completion lanes.
    localparam int ISSUE_WIDTH = 2;
    localparam int NUM_LANES   = 4;

    // How many instructions retired this cycle: 0..ISSUE_WIDTH, so the
    // width is clog2(ISSUE_WIDTH+1), NOT ISSUE_WIDTH-1:0.  Those two happen
    // to both be 2 bit today -- arithmetic coincidence, not meaning.
    localparam int COMMIT_COUNT_W = $clog2(ISSUE_WIDTH + 1);

    // Architectural register-file read ports.  Shapes are frozen:
    // the source number *is* the index and its base is 1, not 0 -- there is no
    // `rs0`.  Every module that carries these ports declares them identically:
    //
    //   INT   [ISSUE_WIDTH][1:INT_SRC_PER_SLOT]   (s,x), s in {0,1}, x in {1,2}
    //   FP    [1:FP_READ_PORTS]                   x in {1,2,3}, no slot dimension
    //
    // Do NOT flatten the INT ports to [4]: flattening makes slot-major vs
    // source-major a second unowned choice, and independently written modules
    // pick differently when a choice is left unowned.
    localparam int INT_SRC_PER_SLOT = 2;
    localparam int INT_READ_PORTS   = ISSUE_WIDTH * INT_SRC_PER_SLOT;   // 4
    localparam int FP_READ_PORTS    = 3;

    // rs_data_sel_t -- one-hot0 source select, the bit order is
    // frozen.  Generated by dependency_check, decoded by the payload assembly; both
    // sides must read the same order or the wrong lane is taken silently.
    //   [6]    sel_arf
    //   [5:4]  sel_commit[1:0]     bit4 = commit lane 0
    //   [3:0]  sel_bypass[3:0]     bit0 = bypass lane 0
    // No typedef here on purpose: `rs_data_sel_t` is a *signal* name
    // (dependency_check, the payload assembly), so a type of that name would shadow
    // the port in every module that imports this package.
    localparam int RS_DATA_SEL_W = 1 + ISSUE_WIDTH + NUM_LANES;         // 7

    // FU index *within* a group, not a global group id.
    localparam int FU_GROUP_W = 2;

    // How many FUs each issue group holds.
    // This is a *count*, not an index width: do not
    // reach for FU_GROUP_W or ISSUE_WIDTH to size a per-requester array just
    // because the number happens to match.
    //   G0  ALU0/BRU, CSR, DIV
    //   G1  ALU1, MUL
    //   G2  FPU        -- single member, no arbiter, completion drives lane 2
    //   G3  LSU        -- outside the DUT, no arbiter, drives lane 3
    localparam int G0_NUM_FU = 3;
    localparam int G1_NUM_FU = 2;
    localparam int G2_NUM_FU = 1;

    // Each FU's identity *within* its group.  This is what a FU compares
    // `FU_Group` against to decide "is this issue for me", and what the top
    // level uses to wire FU k to the arbiter's req_*[k].  A count is not an
    // identity -- G0_NUM_FU says how many, these say which.
    //
    // Note ALU is 0 in both groups: alu_simple is instantiated twice, as
    // ALU0/BRU in G0 and ALU1 in G1.
    localparam int G0_FU_ALU = 0;
    localparam int G0_FU_CSR = 1;
    localparam int G0_FU_DIV = 2;
    localparam int G1_FU_ALU = 0;
    localparam int G1_FU_MUL = 1;

    localparam int MEM_FUNCT3_W = LSU_MEM_F3_W;          // 3, frozen
    localparam int EXE_SUBOP_W  = BACKEND_EXE_SUBOP_W;   // 24, frozen

    // SCB carries a 63-bit cause field; the LSU boundary is 5-bit and
    // zero-extends into it.
    // CSR address field.  RISC-V fixes it at 12 bit.  It also happens to equal
    // FULL_DECODE_W-5 because full_decode packs it in the low bits, but that is
    // arithmetic coincidence, not meaning -- name the quantity.
    localparam int CSR_ADDR_W = 12;

    localparam int EXCP_CAUSE_W = 63;

    // Payload-side fetch-exception cause.  **Deliberately not EXCP_CAUSE_W.**
    // EXCP_CAUSE_W is 63 because a completion lane carries mcause[62:0]; the
    // front end can only ever report an architectural fetch cause (1 =
    // instruction access fault, 12 = instruction page fault, ...), all of
    // which fit in 5 bits, and `fe_be_instr_pld_t.exception_cause` in the TB
    // is 5 bits for the same reason.  Carrying 63 bits of a 0..31 value
    // through two payload stages would cost 116 bit of IB+ISQ payload for
    // nothing.  alu_simple zero-extends to EXCP_CAUSE_W when it drives the
    // completion lane.
    localparam int FETCH_EXCP_CAUSE_W = 5;
    localparam int FFLAGS_W     = 5;
    localparam int FULL_DECODE_W = 17;
    localparam int RECOVERY_KIND_W = 3;

    // Privilege level encoding.  RISC-V fixes it at 2 bit (mstatus.MPP and
    // system_instruction_handler current_priv(2)).  The build implements
    // M, S and U (or_be_config_pkg ENABLE_S / ENABLE_U = 1), so current_priv
    // takes 2'b11 / 2'b01 / 2'b00.
    localparam int PRIV_W = 2;

    // XLEN and the LSU data width are separate concepts that happen to agree.
    // If they ever diverge the payload assembly below is wrong, so pin it.
    localparam bit XLEN_MATCHES_LSU_DATA_W = (XLEN == LSU_DATA_W);

    typedef logic [XLEN-1:0]       xlen_t;
    typedef logic [TAG_W-1:0]      rob_tag_t;
    typedef logic [ROB_PTR_W-1:0]  rob_ptr_t;
    typedef logic [REG_ADDR_W-1:0] reg_addr_t;

    // ---------------------------------------------------------------------
    // full_decode
    // ---------------------------------------------------------------------
    //   [16]    csr_write_intent
    //   [15]    illegal
    //   [14:12] rm
    //   [11:0]  csr_addr
    typedef enum logic [2:0] {
        RM_RNE = 3'b000,
        RM_RTZ = 3'b001,
        RM_RDN = 3'b010,
        RM_RUP = 3'b011,
        RM_RMM = 3'b100,
        RM_RSV5 = 3'b101,   // reserved
        RM_RSV6 = 3'b110,   // reserved
        RM_DYN = 3'b111     // FPU takes SIH's frm at issue
    } rm_e;

    typedef struct packed {
        logic        csr_write_intent;
        logic        illegal;
        rm_e         rm;
        logic [11:0] csr_addr;
    } full_decode_t;

    function automatic logic rm_is_reserved(input rm_e rm);
        return (rm == RM_RSV5) || (rm == RM_RSV6);
    endfunction

    // ---------------------------------------------------------------------
    // IB_Payload -- 294 bit
    // ---------------------------------------------------------------------
    // **The queue stores exactly the 11 fields FE sends in, bit for bit, not
    // one more and not one less.**
    //
    // That is, **FE -> IB is pure wiring**: no RVC expansion on this path, no
    // decode, no decision at all, not even the fetch_excp clear mask. The
    // constraint comes from measurement -- the fetch cycle (FE flop -> IB
    // flop) cannot fit even one RVC expander, so **any decode-related logic
    // on the BE side must come after the IB**; the enqueue side does no
    // expansion.
    // RVC expansion and Operand_Extract are done in FE's own pipeline stage
    // (or_fe_pkg::rvc_expand / operand_extract),
    // and the results enqueue with the entry as the three fields
    // inst_expanded / rvc_ill / opnd; FE -> IB is still pure wiring.
    //
    // Two parallel branches on the dequeue side:
    //   address branch  opnd.rs1/rs2/rs3/rd -> ARF / tag_mapping read
    //                   (backend_top glue logic #1, no combinational logic)
    //   decode branch   inst_expanded -> [full decode] -> decoded_info_t
    // There is no expander inside BE; register numbers and the expanded word
    // come from the same or_fe_pkg source as in FE.
    //
    // 294 = RAW fields 232 + inst_expanded 32 + rvc_ill 1 + opnd 29 (20 bits of
    // register numbers + 9 flag bits). Decode products are not enqueued; they
    // are produced by decode on the dequeue side (decoded_info_t).
    //
    // `inst_bits` is in **RAW form**, bit-identical to what FE sends (a
    // compressed instruction is `{16'b0, original halfword}`). The mtval of an
    // illegal instruction must be the encoding that really exists in the
    // program; the expansion result is not something in the program.
    // ISQ_Payload passes it straight through, so the tval logic of the four
    // FUs needs not a single line changed.
    //
    // The field set is the same as fe_be_protocol_pkg::fe_be_instr_pld_t; equal
    // width is pinned by or_be_types_check (this package cannot import that
    // package -- the dependency direction is the other way).
    // ---------------------------------------------------------------------
    // operand_info -- product of FE Operand_Extract
    // ---------------------------------------------------------------------
    // Field order is bit-identical to or_fe_pkg::operand_info_t. Register
    // numbers are fixed slices of the expanded word; use_* / *_is_fp are **not
    // gated** -- on illegal / fetch exception backend_top glue logic #1 gates
    // them uniformly with decode's full_decode.illegal. is_fp_opcode looks only
    // at the opcode and is never gated: it feeds both dependency_check's
    // fp0/fp1 and FP_read_address_mux's select bit.
    typedef struct packed {
        logic [REG_ADDR_W-1:0] rs1;
        logic [REG_ADDR_W-1:0] rs2;
        logic [REG_ADDR_W-1:0] rs3;
        logic [REG_ADDR_W-1:0] rd;
        logic               use_rs1;
        logic               use_rs2;
        logic               use_rs3;
        logic               use_rd;
        logic               rs1_is_fp;
        logic               rs2_is_fp;
        logic               rs3_is_fp;
        logic               rd_is_fp;
        logic               is_fp_opcode;
    } ib_operand_info_t;

    typedef struct packed {
        // instruction identity
        xlen_t              pc;
        logic [31:0]        inst_bits;
        logic               is_compressed;
        // RVC expansion and operand extraction are in FE.
        // inst_expanded is FE's expanded 32-bit word (decode's ib_inst32);
        // rvc_ill means the compressed encoding is illegal; opnd connects
        // directly to ARF / tag_mapping / dependency_check.
        // inst_bits stays RAW (mtval and the SUBOP_C_* compressed aliases both
        // need the original encoding).
        logic [31:0]        inst_expanded;
        logic               rvc_ill;
        ib_operand_info_t   opnd;
        // branch prediction
        logic               pred_taken;
        xlen_t              pred_target_pc;
        // fetch-side exception
        // Set when the front end could not fetch this PC at all.  `inst_bits`
        // is then meaningless, so decode forces this entry onto G0 with no
        // sources and no destination -- see decode.sv.
        logic                            fetch_excp_vld;
        logic [FETCH_EXCP_CAUSE_W-1:0]   fetch_excp_cause;
        xlen_t                           fetch_excp_tval;
    } ib_payload_t;

    localparam int IB_PAYLOAD_W = $bits(ib_payload_t);

    // ---------------------------------------------------------------------
    // decoded_info -- 112 bit, every decode product that decode produces on
    // the **dequeue side**
    // ---------------------------------------------------------------------
    // **There is no rs*_idx / rd_idx here, and no use_* / *_is_fp.** They are
    // all fields of the IB entry's `opnd` (FE Operand_Extract), taken by
    // backend_top glue logic #1 straight from the IB head to the register
    // read, **without going through decode** -- that is the whole of "the
    // register read starts early": the address path reads only the IB head
    // entry itself (register storage comes straight out of the rptr read
    // port), without waiting for full decode (deep).
    //
    // The indices are **not gated by the illegal clear** (use_* /
    // *_is_fp are gated by glue logic #1 with full_decode.illegal).
    // Safety is guaranteed on the consumer side, checked one by one:
    //   dependency_check        rd_write_enable = use_rd && ...   → use_rd
    //                           dominates
    //   dependency_check        slot1_dep_hit doubly qualified by
    //                           rd_write_enable[SLOT0] and use_rs[SLOT1][x]
    //   INT/FP_tag_mapping      alloc gated by rd_write_enable
    //   ARF / tag_mapping read  combinational read, no side effect, output
    //                           masked by use_rs*
    //   isq_payload_t           carries no index at all
    typedef struct packed {
        logic               is_serial;
        logic               is_fp_instruction;
        // use_rs* / use_rd / rs*_is_fp / rd_is_fp are not here; they come from
        // the IB entry's opnd (FE Operand_Extract), for gating see backend_top
        // glue logic #1.
        // memory sideband (G3 only)
        logic               is_store;          // plain store only
        logic [MEM_FUNCT3_W-1:0] mem_funct3;
        // immediate: already fully sign-extended by decode
        logic               imm_valid;
        logic signed [XLEN-1:0] imm_data;
        // decode results
        backend_exe_subop_t exe_subop;
        full_decode_t       full_decode;
    } decoded_info_t;

    localparam int DECODED_INFO_W = $bits(decoded_info_t);

    // ---------------------------------------------------------------------
    // ISQ_Payload -- 556 bit
    // ---------------------------------------------------------------------
    // Assembly-side overwrite: full_decode.rm is replaced by dispatch_logic's
    // effective_rm before entering the payload; the other 14 bits pass through.
    typedef struct packed {
        // operands
        xlen_t     rs1_data;
        xlen_t     rs2_data;
        xlen_t     rs3_data;
        logic      rs1_ready;
        logic      rs2_ready;
        logic      rs3_ready;
        rob_tag_t  rs1_wait_tag;
        rob_tag_t  rs2_wait_tag;
        rob_tag_t  rs3_wait_tag;
        // routing
        rob_tag_t              self_tag;
        logic [FU_GROUP_W-1:0] fu_group;
        // immediate
        logic      imm_valid;
        logic signed [XLEN-1:0] imm_data;
        // instruction identity + prediction
        xlen_t       pc;
        logic [31:0] inst_bits;
        logic        is_compressed;
        logic        pred_taken;
        xlen_t       pred_target_pc;
        // memory sideband
        logic                    is_store;
        logic [MEM_FUNCT3_W-1:0] mem_funct3;
        logic                    rd_is_fp;
        // decode results
        backend_exe_subop_t exe_subop;
        full_decode_t       full_decode;
        // fetch-side exception -- passes through unchanged from IB_Payload
        logic                            fetch_excp_vld;
        logic [FETCH_EXCP_CAUSE_W-1:0]   fetch_excp_cause;
        xlen_t                           fetch_excp_tval;
    } isq_payload_t;

    localparam int ISQ_PAYLOAD_W = $bits(isq_payload_t);

    // ---------------------------------------------------------------------
    // completion_common -- the shape all four lanes drive
    // ---------------------------------------------------------------------
    // Lane constraints:
    //   G1  event fields all zero
    //   G2  exception / mispredict / is_mret / is_sret zero, drives fpu_fflags
    //   G3  only memory synchronous exceptions; mispredict / is_mret / is_sret /
    //       fflags zero
    // Zero fields are driven by the FU itself -- the arbiter never fills them in.
    typedef struct packed {
        logic                       result_valid;
        rob_tag_t                   tag_out;
        xlen_t                      result_data;
        logic                       mispredict_flag;
        xlen_t                      mispredict_target_pc;
        logic                       exception_flag;
        logic [EXCP_CAUSE_W-1:0]    exception_cause;
        xlen_t                      exception_tval;
        logic                       is_mret;
        // SRET.  Mutually exclusive with is_mret -- flush_model picks
        // sepc vs mepc from which one is set.
        logic                       is_sret;
        logic [FFLAGS_W-1:0]        fpu_fflags;
    } completion_common_t;

    // Result broadcast on the 4-lane CDB.
    typedef struct packed {
        logic     bypass_valid;
        rob_tag_t bypass_tag;
        xlen_t    bypass_data;
    } bypass_lane_t;

    // ---------------------------------------------------------------------
    // SCB alloc batch -- written once at alloc, never overwritten by P3
    // ---------------------------------------------------------------------
    // `st_br_resolve` is NOT part of this batch: the SCB computes it itself at
    // alloc from the safe-prefix scan, and no module drives it in.
    typedef struct packed {
        reg_addr_t rd_idx;
        logic      rd_is_fp;
        logic      rd_write_enable;
        logic      is_store;        // plain store only; AMO/SC are 0 here
        logic      is_fence_i;
        logic      may_flush;
        logic      is_atomic;       // LR / SC / AMO, from is_g3_atomic_subop()
    } scb_alloc_batch_t;

    // ---------------------------------------------------------------------
    // Commit bus -- lane 0 is always head0, lane 1 always head1, no compaction
    // ---------------------------------------------------------------------
    typedef struct packed {
        logic                commit_valid;
        rob_tag_t            commit_tag;
        reg_addr_t           rd_idx;
        logic                rd_is_fp;
        logic                rd_write_enable;
        logic [FFLAGS_W-1:0] commit_fflags;
    } commit_lane_t;

    // ---------------------------------------------------------------------
    // Flush / recovery
    // ---------------------------------------------------------------------
    typedef enum logic [RECOVERY_KIND_W-1:0] {
        RECOVERY_MISPREDICT = 3'd0,
        RECOVERY_EXCEPTION  = 3'd1,
        RECOVERY_MRET       = 3'd2,
        RECOVERY_INTERRUPT  = 3'd3,
        RECOVERY_FENCE_I    = 3'd4,
        // RECOVERY_KIND_W is 3, so SRET fits without a width change.
        RECOVERY_SRET       = 3'd5
        // 5..7 reserved
    } recovery_kind_e;

    typedef struct packed {
        logic                    valid;
        recovery_kind_e          kind;
        xlen_t                   epc;
        logic [EXCP_CAUSE_W-1:0] cause;
        xlen_t                   tval;
    } trap_state_write_t;

    // ---------------------------------------------------------------------
    // predictor_update -- G0's BRU trains the front-end predictor from the
    // execute stage directly, without waiting for commit.
    // ---------------------------------------------------------------------
    // The bundle is {valid, branch_pc(64), actual_taken,
    // actual_target(64), cf_class(2)}; cf_class comes from exe_subop
    // and carries **no call/return** -- this backend has no RAS.  The
    // taxonomy of the two bits is fixed here: the three
    // shapes a predictor actually needs to tell apart, plus a reserved code.
    localparam int CF_CLASS_W = 2;
    typedef enum logic [CF_CLASS_W-1:0] {
        CF_COND_BRANCH = 2'd0,   // BEQ/BNE/BLT/BGE/BLTU/BGEU, C_BEQZ, C_BNEZ
        CF_JUMP_DIRECT = 2'd1,   // JAL, C_J  (C_JAL is RV32-only, not in the frozen pkg)
        CF_JUMP_INDIRECT = 2'd2, // JALR, C_JR, C_JALR
        CF_RESERVED    = 2'd3
    } cf_class_e;

    // Register identity used where integer and FP files must be told apart in
    // one comparison: bit REG_ADDR_W selects the file (0 = INT, 1 = FP).
    localparam int REG_ID_W = REG_ADDR_W + 1;
    typedef logic [REG_ID_W-1:0] reg_id_t;

    function automatic reg_id_t reg_id(input logic is_fp, input reg_addr_t idx);
        return {is_fp, idx};
    endfunction

endpackage

`endif // OR_BE_TYPES_PKG_SV
